table 'RAW DATA'
	lineageTag: 640eea78-1b9f-42a7-a97a-5ad26f84a9dd

	column Number
		dataType: string
		lineageTag: 6d3bca01-73e5-42ea-8774-36cdaa6d8490
		summarizeBy: none
		sourceColumn: Number

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: DD-MMM-YYYY
		lineageTag: cbd23a9b-6447-4c40-bcd5-9a427d39f800
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 8faeeec9-1594-43d8-88f4-1dea28401152
			defaultHierarchy: LocalDateTable_8fbec8e9-fe95-464e-8940-7a8334e33e2b.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Priority
		dataType: string
		lineageTag: 32ece9dc-50c9-4728-bdf1-7543914dd1e8
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6d0203e5-9df3-4071-96c6-e059a6a3ec15
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Assignment group'
		dataType: string
		lineageTag: 901228a7-f734-49ff-a79a-17c3d0188cda
		summarizeBy: none
		sourceColumn: Assignment group
		sortByColumn: 'Assignment Group Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Assigned to'
		dataType: string
		lineageTag: 6fed1ce7-a0b5-466f-b796-a0e0c90c9ccd
		summarizeBy: none
		sourceColumn: Assigned to

		annotation SummarizationSetBy = Automatic

	column Updated
		dataType: dateTime
		formatString: DD-MMM-YYYY
		lineageTag: 8d32605a-204d-4303-9822-85e8eaf3eee1
		summarizeBy: none
		sourceColumn: Updated

		variation Variation
			isDefault
			relationship: 52995061-0207-492e-b2f5-3b843b4829b4
			defaultHierarchy: LocalDateTable_50243b39-69ae-429d-958e-5ec35e943e7a.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Short description'
		dataType: string
		lineageTag: a01b49bd-8ce6-4174-9dc0-46b00304907b
		summarizeBy: none
		sourceColumn: Short description

		annotation SummarizationSetBy = Automatic

	column 'On hold reason'
		dataType: string
		lineageTag: 0140b5c6-5156-41a4-a9d4-21b946fc8e31
		summarizeBy: none
		sourceColumn: On hold reason

		annotation SummarizationSetBy = Automatic

	column 'Reopen count'
		dataType: int64
		formatString: 0
		lineageTag: 8896f654-fd5d-4c0f-bab3-c50a5ec10081
		summarizeBy: sum
		sourceColumn: Reopen count

		annotation SummarizationSetBy = Automatic

	column 'Reassignment count'
		dataType: int64
		formatString: 0
		lineageTag: 1fccc346-352c-424a-8560-2a1f924f80eb
		summarizeBy: sum
		sourceColumn: Reassignment count

		annotation SummarizationSetBy = Automatic

	column 'INC. AGE'
		dataType: double
		lineageTag: 298ddeac-46a7-4065-a59c-ba3d35549e8c
		summarizeBy: sum
		sourceColumn: INC. AGE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AGE BIN'
		dataType: string
		lineageTag: fb9ef07f-b0ba-4c5c-9247-1455d4958887
		summarizeBy: none
		sourceColumn: AGE BIN
		sortByColumn: 'BIN SORT'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Assignment Group Sort'
		dataType: int64
		formatString: 0
		lineageTag: 39d791ac-e19c-4a1d-8125-7b4815706c78
		summarizeBy: sum
		sourceColumn: Assignment Group Sort

		annotation SummarizationSetBy = Automatic

	column 'BIN SORT'
		dataType: int64
		formatString: 0
		lineageTag: ab7113b5-73d1-402d-9646-8639f91c1f5b
		summarizeBy: sum
		sourceColumn: BIN SORT

		annotation SummarizationSetBy = Automatic

	column DAYTIMECHECK =
			
			VAR DayOfWeek = WEEKDAY('RAW DATA'[Created], 2)  -- 2 makes Monday = 1, Sunday = 7
			VAR TimeOfDay = TIMEVALUE('RAW DATA'[Created])  -- Extracts the time portion
			VAR StartTime = TIME(8, 30, 0)  -- 8:30 AM
			VAR EndTime = TIME(21, 30, 0)   -- 9:30 PM
			RETURN
			    IF(
			        DayOfWeek >= 1 && DayOfWeek <= 5 && TimeOfDay >= StartTime && TimeOfDay <= EndTime,
			        TRUE(),
			        FALSE()
			    )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6ad07172-3f0e-4611-919b-ad6b351a587d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Yr-Mnth = FORMAT('RAW DATA'[Created], "YYYY-MMM")
		lineageTag: abc2483f-940c-45ec-834b-4d46fda30f33
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'TEAM NAME'
		dataType: string
		lineageTag: 25d73c25-47e2-48f0-a293-0bce7ca924ab
		summarizeBy: none
		sourceColumn: TEAM NAME

		annotation SummarizationSetBy = Automatic

	column Prty
		dataType: string
		lineageTag: bd3fc0df-5074-47ba-9596-a0b44bcac335
		summarizeBy: none
		sourceColumn: Prty

		annotation SummarizationSetBy = Automatic

	partition 'RAW DATA' = m
		mode: import
		source =
				let
				    Source = #table(
				        type table [Number = text, Created = datetime, Priority = text, State = text, Assignment group = text, Assigned to = text, Updated = datetime, Short description = text, On hold reason = text, Reopen count = Int64.Type, Reassignment count = Int64.Type],
				        {
				            {"MOCK-000001", #datetime(2025, 1, 6, 8, 45, 0), "1 - Critical", "Resolved", "Platform Alpha", "Mock User 01", #datetime(2025, 1, 6, 14, 20, 0), "Synthetic connectivity issue", null, 0, 1},
				            {"MOCK-000002", #datetime(2025, 1, 8, 10, 15, 0), "2 - High", "Closed", "Platform Beta", "Mock User 02", #datetime(2025, 1, 9, 16, 40, 0), "Synthetic access request", null, 0, 0},
				            {"MOCK-000003", #datetime(2025, 1, 13, 9, 30, 0), "3 - Moderate", "In Progress", "Cloud Operations", "Mock User 03", #datetime(2025, 2, 18, 11, 0, 0), "Synthetic service configuration issue", "Awaiting Evidence", 1, 2},
				            {"MOCK-000004", #datetime(2025, 1, 17, 13, 5, 0), "4 - Low", "On Hold", "Data Services", "Mock User 04", #datetime(2025, 2, 20, 15, 35, 0), "Synthetic data refresh issue", "Awaiting Vendor", 0, 1},
				            {"MOCK-000005", #datetime(2025, 1, 21, 15, 20, 0), "5 - Planning", "Canceled", "Customer Support", "Mock User 05", #datetime(2025, 1, 22, 9, 10, 0), "Synthetic notification request", null, 0, 0},
				            {"MOCK-000006", #datetime(2025, 2, 3, 8, 35, 0), "1 - Critical", "Closed", "Integration Hub", "Mock User 06", #datetime(2025, 2, 3, 18, 25, 0), "Synthetic integration outage", null, 0, 1},
				            {"MOCK-000007", #datetime(2025, 2, 7, 11, 50, 0), "2 - High", "Resolved", "Platform Alpha", "Mock User 07", #datetime(2025, 2, 10, 12, 30, 0), "Synthetic performance issue", null, 0, 0},
				            {"MOCK-000008", #datetime(2025, 2, 12, 14, 10, 0), "3 - Moderate", "In Progress", "Platform Beta", "Mock User 08", #datetime(2025, 3, 20, 10, 45, 0), "Synthetic workflow issue", "Awaiting Caller", 0, 1},
				            {"MOCK-000009", #datetime(2025, 2, 18, 9, 5, 0), "4 - Low", "Closed", "Cloud Operations", "Mock User 09", #datetime(2025, 2, 19, 17, 25, 0), "Synthetic monitoring alert", null, 0, 0},
				            {"MOCK-000010", #datetime(2025, 2, 24, 16, 30, 0), "5 - Planning", "Resolved", "Data Services", "Mock User 10", #datetime(2025, 3, 3, 13, 15, 0), "Synthetic reporting request", null, 0, 1},
				            {"MOCK-000011", #datetime(2025, 3, 3, 8, 55, 0), "1 - Critical", "Canceled", "Customer Support", "Mock User 11", #datetime(2025, 3, 4, 9, 20, 0), "Synthetic endpoint issue", null, 0, 0},
				            {"MOCK-000012", #datetime(2025, 3, 11, 10, 40, 0), "2 - High", "On Hold", "Integration Hub", "Mock User 12", #datetime(2025, 4, 22, 14, 5, 0), "Synthetic vendor dependency", "Awaiting Vendor", 1, 2},
				            {"MOCK-000013", #datetime(2025, 3, 19, 12, 25, 0), "3 - Moderate", "Closed", "Platform Alpha", "Mock User 13", #datetime(2025, 3, 25, 16, 50, 0), "Synthetic account issue", null, 0, 0},
				            {"MOCK-000014", #datetime(2025, 3, 27, 9, 15, 0), "4 - Low", "Resolved", "Platform Beta", "Mock User 14", #datetime(2025, 4, 2, 11, 35, 0), "Synthetic form submission issue", null, 0, 1},
				            {"MOCK-000015", #datetime(2025, 4, 4, 15, 45, 0), "5 - Planning", "In Progress", "Cloud Operations", "Mock User 15", #datetime(2025, 5, 12, 10, 10, 0), "Synthetic enhancement request", "Awaiting Problem", 0, 1},
				            {"MOCK-000016", #datetime(2025, 4, 14, 8, 25, 0), "1 - Critical", "Closed", "Data Services", "Mock User 16", #datetime(2025, 4, 14, 19, 0, 0), "Synthetic data availability issue", null, 0, 0},
				            {"MOCK-000017", #datetime(2025, 4, 21, 10, 5, 0), "2 - High", "Resolved", "Customer Support", "Mock User 17", #datetime(2025, 4, 24, 15, 40, 0), "Synthetic customer portal issue", null, 0, 1},
				            {"MOCK-000018", #datetime(2025, 5, 2, 13, 35, 0), "3 - Moderate", "On Hold", "Integration Hub", "Mock User 18", #datetime(2025, 6, 16, 9, 50, 0), "Synthetic integration dependency", "Awaiting Change", 0, 2},
				            {"MOCK-000019", #datetime(2025, 5, 9, 9, 45, 0), "4 - Low", "Closed", "Platform Alpha", "Mock User 19", #datetime(2025, 5, 13, 14, 30, 0), "Synthetic knowledge request", null, 0, 0},
				            {"MOCK-000020", #datetime(2025, 5, 20, 16, 15, 0), "5 - Planning", "Resolved", "Platform Beta", "Mock User 20", #datetime(2025, 5, 29, 12, 20, 0), "Synthetic access review", null, 0, 0}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Number", type text}, {"Created", type datetime}, {"Priority", type text}, {"State", type text}, {"Assignment group", type text}, {"Assigned to", type text}, {"Updated", type datetime}, {"Short description", type text}, {"On hold reason", type any}, {"Reopen count", Int64.Type}, {"Reassignment count", Int64.Type}}),
				    #"AGE INCIDENT" = Table.AddColumn(#"Changed Type", "INC. AGE", each [Updated]-[Created]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"AGE INCIDENT",{{"INC. AGE", type number}}),
				    #"Age Bin" = Table.AddColumn(#"Changed Type1", "AGE BIN", each if [INC. AGE] = 30 then "30 days" else if [INC. AGE] < 30 then "Less than 30 days" else if [INC. AGE] <= 60 then "31-60 days" else "60+ days"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Age Bin",{{"AGE BIN", type text}}),
				    #"Assignment Group Sort" = Table.AddColumn(#"Changed Type2", "Assignment Group Sort", each if [Assignment group] = "Platform Alpha" then 1 else if [Assignment group] = "Platform Beta" then 2 else if [Assignment group] = "Cloud Operations" then 3 else if [Assignment group] = "Data Services" then 4 else if [Assignment group] = "Customer Support" then 5 else if [Assignment group] = "Integration Hub" then 6 else 7),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Assignment Group Sort",{{"Assignment Group Sort", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type3", "BIN SORT", each if [AGE BIN] = "Less than 30 days" then 1 else if [AGE BIN] = "30 days" then 2 else if [AGE BIN] = "31-60 days" then 3 else if [AGE BIN] = "60+ days" then 4 else 5),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Conditional Column",{{"BIN SORT", Int64.Type}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Changed Type4", "TEAM NAME", each if [Assignment group] = "Platform Alpha" then "PLATFORM ALPHA" else if [Assignment group] = "Platform Beta" then "PLATFORM BETA" else if [Assignment group] = "Cloud Operations" then "CLOUD OPERATIONS" else if [Assignment group] = "Data Services" then "DATA SERVICES" else if [Assignment group] = "Customer Support" then "CUSTOMER SUPPORT" else if [Assignment group] = "Integration Hub" then "INTEGRATION HUB" else "OTHER"),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"TEAM NAME", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type5", "Priority", "Priority - Copy"),
				    #"Extracted First Characters" = Table.TransformColumns(#"Duplicated Column", {{"Priority - Copy", each Text.Start(_, 1), type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted First Characters",{{"Priority - Copy", "Prty"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","4","P4",Replacer.ReplaceText,{"Prty"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","P1",Replacer.ReplaceText,{"Prty"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","2","P2",Replacer.ReplaceText,{"Prty"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value2", each true),
				    #"Replaced Value3" = Table.ReplaceValue(#"Filtered Rows","3","P3",Replacer.ReplaceText,{"Prty"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","5","P5",Replacer.ReplaceText,{"Prty"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value4", each true)
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

